#!/usr/bin/env python3
"""
This script lists all databases in MongoDB.
"""

from pymongo import MongoClient


def list_databases():
    """Lists all databases in MongoDB."""
    client = MongoClient()
    databases = client.list_database_names()
    print("Databases:")
    for db in databases:
        print(f"- {db}")


if __name__ == "__main__":
    list_databases()
